spring.datasource.url=jdbc:mysql://localhost:3306/nbp1
spring.datasource.username=root
spring.datasource.password=Pjatk&*&&^&
spring.jpa.hibernate.ddl-auto=create
springdoc.swagger-ui.path=/swagger-ui.html
